# =============================================================================
# APPLICATION-SPECIFIC CONFIGURATION
# =============================================================================

CONFIG_TOPIC_PREFIX="adc"
CONFIG_TOPIC_PUBLISH_PERIOD_MS=1000

CONFIG_MICROROS_NODES="1"
CONFIG_MICROROS_PUBLISHERS="8"
CONFIG_MICROROS_SUBSCRIBERS="1"
# CONFIG_MICROROS_CLIENTS="1"
# CONFIG_MICROROS_SERVERS="1"
CONFIG_MICROROS_RMW_HISTORIC="4"
# CONFIG_MICROROS_XRCE_DDS_MTU="512"
# CONFIG_MICROROS_XRCE_DDS_HISTORIC="4"

# =============================================================================
# CORE SYSTEM CONFIGURATION
# =============================================================================

CONFIG_GPIO=y
CONFIG_ADC=y

# =============================================================================
# MICROROS LIBRARY
# =============================================================================
CONFIG_GPIO=y
CONFIG_MICROROS=y
CONFIG_CPP=y

CONFIG_MAIN_STACK_SIZE=25000
CONFIG_MAIN_THREAD_PRIORITY=3

CONFIG_NEWLIB_LIBC=y
CONFIG_NEWLIB_LIBC_NANO=n
CONFIG_PTHREAD_IPC=n

CONFIG_POSIX_API=y
CONFIG_POSIX_CLOCK=y

CONFIG_STDOUT_CONSOLE=y
CONFIG_LOG=y
CONFIG_SERIAL=y
CONFIG_UART_INTERRUPT_DRIVEN=y
CONFIG_UART_LINE_CTRL=y